<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="ApiTest" duration-ms="15636" started-at="2015-08-30T14:11:20Z" finished-at="2015-08-30T14:11:36Z">
    <groups>
    </groups>
    <test name="ApiTest" duration-ms="15636" started-at="2015-08-30T14:11:20Z" finished-at="2015-08-30T14:11:36Z">
      <class name="com.kaikeba.server.api.utils.HTTPRequestTest">
        <test-method status="PASS" signature="initDataPath(java.lang.String, java.lang.String)[pri:0, instance:com.kaikeba.server.api.utils.HTTPRequestTest@78e94dcf]" name="initDataPath" is-config="true" duration-ms="12702" started-at="2015-08-30T22:11:20Z" finished-at="2015-08-30T22:11:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[data.xls]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDataPath -->
        <test-method status="FAIL" signature="run(java.lang.String, com.gxb.server.api.beans.InputData)[pri:0, instance:com.kaikeba.server.api.utils.HTTPRequestTest@78e94dcf]" name="run" duration-ms="2276" started-at="2015-08-30T22:11:33Z" data-provider="iterator" finished-at="2015-08-30T22:11:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[InputData [ID=3.0, testCase=3.0, description=3.0, host=http://w-api-h1.kaikeba.com, callSuff=/tenants/1/classes?curPage=1&pageSize=5&sort=enrollments_count-,created_at, callType=GET, authScheme= , authCreds= , accept= , contentType= , body= , ActualResponse=<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="3;url=http://www.kaikeba.com">
    <title>404</title>
    <style>
        body{
            background: #fffffe;
        }
        .unpage{
            text-align: center;
            padding-top: 196px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="unpage">
        <img alt="404" src="/assets/images/404.jpg" >
    </div>
</div>
</body>
</html>, ExpectResponse= , log= , IsPass=No]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[第3行数据，接口测试失败！]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 第3行数据，接口测试失败！
	at org.testng.Assert.fail(Assert.java:94)
	at com.kaikeba.server.api.utils.HTTPRequestTest.run(HTTPRequestTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
        <test-method status="FAIL" signature="run(java.lang.String, com.gxb.server.api.beans.InputData)[pri:0, instance:com.kaikeba.server.api.utils.HTTPRequestTest@78e94dcf]" name="run" duration-ms="95" started-at="2015-08-30T22:11:35Z" data-provider="iterator" finished-at="2015-08-30T22:11:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[InputData [ID=1.0, testCase=1.0, description=1.0, host=http://w-api-h1.kaikeba.com, callSuff=/tenants/1/classes?curPage=1&pageSize=5&sort=enrollments_count-,created_at, callType=GET, authScheme= , authCreds= , accept= , contentType= , body= , ActualResponse=<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="3;url=http://www.kaikeba.com">
    <title>404</title>
    <style>
        body{
            background: #fffffe;
        }
        .unpage{
            text-align: center;
            padding-top: 196px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="unpage">
        <img alt="404" src="/assets/images/404.jpg" >
    </div>
</div>
</body>
</html>, ExpectResponse= , log= , IsPass=No]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[第1行数据，接口测试失败！]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 第1行数据，接口测试失败！
	at org.testng.Assert.fail(Assert.java:94)
	at com.kaikeba.server.api.utils.HTTPRequestTest.run(HTTPRequestTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
        <test-method status="FAIL" signature="run(java.lang.String, com.gxb.server.api.beans.InputData)[pri:0, instance:com.kaikeba.server.api.utils.HTTPRequestTest@78e94dcf]" name="run" duration-ms="91" started-at="2015-08-30T22:11:35Z" data-provider="iterator" finished-at="2015-08-30T22:11:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[InputData [ID=2.0, testCase=2.0, description=2.0, host=http://w-api-h1.kaikeba.com, callSuff=/tenants/1/classes?curPage=1&pageSize=5&sort=enrollments_count-,created_at, callType=GET, authScheme= , authCreds= , accept= , contentType= , body= , ActualResponse=<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="3;url=http://www.kaikeba.com">
    <title>404</title>
    <style>
        body{
            background: #fffffe;
        }
        .unpage{
            text-align: center;
            padding-top: 196px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="unpage">
        <img alt="404" src="/assets/images/404.jpg" >
    </div>
</div>
</body>
</html>, ExpectResponse= , log= , IsPass=No]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[第2行数据，接口测试失败！]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 第2行数据，接口测试失败！
	at org.testng.Assert.fail(Assert.java:94)
	at com.kaikeba.server.api.utils.HTTPRequestTest.run(HTTPRequestTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
      </class> <!-- com.kaikeba.server.api.utils.HTTPRequestTest -->
    </test> <!-- ApiTest -->
  </suite> <!-- ApiTest -->
</testng-results>
